before_commands:
    - "composer install --dev --prefer-source"

tools:
    external_code_coverage:
        enabled: true
        timeout: 600
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
        filter:
            paths: ["src/*"]
    php_sim:
        enabled: true
    php_cpd:
        enabled: false
        excluded_dirs: ["build/*", "test", "vendor"]
    php_cs_fixer:
        enabled: true
        config:
            level: all
        filter:
            paths: ["src/*"]
    php_loc:
        enabled: true
        excluded_dirs: ["build", "test", "vendor"]
    php_mess_detector:
        enabled: true
        filter:
            paths: ["src/*"]
    php_pdepend:
        enabled: true
        excluded_dirs: ["build", "test", "vendor"]
    php_analyzer:
        enabled: true
        filter:
            paths: ["src/*"]
    sensiolabs_security_checker: true

checks:
    php:
        code_rating: true
        duplication: true


# Use new PHP Analysis Engine.
# https://scrutinizer-ci.com/docs/tools/php/php-scrutinizer/
# https://scrutinizer-ci.com/docs/tools/php/php-analyzer/guides/migrate_to_new_php_analysis
build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
