language: php
dist: trusty
sudo: required

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly

before_script:
  - sudo add-apt-repository -y ppa:crate/stable
  - sudo apt-get update -qq
  - sudo apt-get install -y crate
  - composer self-update
  - composer install --prefer-source

script:
  - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./build/logs/clover.xml

notifications:
  irc: false
  email: false
