name: Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  tests:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-18.04' ] #, macos-latest, windows-latest ]
        php-version: [ '7.3', '7.4', '8.0' ]

    # https://docs.github.com/en/free-pro-team@latest/actions/guides/about-service-containers
    services:
      cratedb:
        image: crate/crate:nightly
        ports:
          - 4200:4200

    # https://github.com/marketplace/actions/setup-php-action
    name: PHP ${{ matrix.php-version }} on OS ${{ matrix.os }}
    steps:

      - name: Acquire sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          # Select PHPUnit version suitable for PHP 7.2.
          tools: composer, phpunit:^8.5

      - uses: ramsey/composer-install@v1

      # Remark: --prefer-source is needed for "Doctrine\Tests\DBAL\Platforms\AbstractPlatformTestCase"
      - name: Install doctrine/dbal from source
        run: |
          rm -rf vendor/doctrine/dbal
          composer update doctrine/dbal --prefer-source

      - name: Run code style checks
        run: composer run check-style

      - name: Run tests
        run: composer run test

      # https://github.com/codecov/codecov-action
      - name: Upload coverage results to Codecov
        uses: codecov/codecov-action@v2
        if: always() && (matrix.php-version == '7.4' || matrix.php-version == '8.0')
        with:
          files: ./build/logs/clover.xml
          fail_ci_if_error: true

      - name: Upload coverage results to Scrutinizer CI
        if: always() && (matrix.php-version == '7.4' || matrix.php-version == '8.0')
        run: |
          composer global require scrutinizer/ocular
          ocular code-coverage:upload --format=php-clover build/logs/clover.xml
